version: '3.8'

services:
  ingestion-stream:
    build:
      context: .
      dockerfile: Dockerfile.ingestion
    command: uvicorn src.ingestion.stream_listener:app --host 0.0.0.0 --port 8000
    volumes:
      - ./raw_data:/app/raw_data
    ports:
      - "8000:8000"
    environment:
      - ENV=dev

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fintech_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
